version: '3.8'

services:
  app:
    build: ./
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1qw23er4
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
